/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author atha3
 */
public class Dashboard extends javax.swing.JPanel {
    private final controller.TransactionController transCtr = new controller.TransactionController();
    private final controller.ProductController prodCtr = new controller.ProductController();
    private final controller.CustomerController custCtr = new controller.CustomerController();

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        reload();
    }
    
    public void reload() {
        long countProducts = prodCtr.countProducts();
        long countTransactions = transCtr.countTransactions();
        long countIncome = transCtr.countIncome();
        long countCustomers = custCtr.countCustomers();
        
        totalProducts.setText(String.valueOf(countProducts));
        totalTransactions.setText(String.valueOf(countTransactions));
        totalIncome.setText("Rp. " + String.valueOf(countIncome));
        totalCustomers.setText(String.valueOf(countCustomers));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardTitle = new javax.swing.JLabel();
        totalTransactionsLabel = new javax.swing.JLabel();
        totalTransactions = new javax.swing.JLabel();
        totalIncomeLabel = new javax.swing.JLabel();
        totalIncome = new javax.swing.JLabel();
        totalCustomersLabel = new javax.swing.JLabel();
        totalCustomers = new javax.swing.JLabel();
        totalProductsLabel = new javax.swing.JLabel();
        totalProducts = new javax.swing.JLabel();

        dashboardTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitle.setText("Dashboard");

        totalTransactionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalTransactionsLabel.setText("Total Transactions:");

        totalTransactions.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalTransactions.setText("0");

        totalIncomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalIncomeLabel.setText("Total Income");

        totalIncome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalIncome.setText("Rp.");

        totalCustomersLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCustomersLabel.setText("Total Customers:");

        totalCustomers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalCustomers.setText("0");

        totalProductsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalProductsLabel.setText("Total Products:");

        totalProducts.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalProducts.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTransactionsLabel)
                    .addComponent(totalIncomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalIncome)
                    .addComponent(totalTransactions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalCustomersLabel)
                    .addComponent(totalProductsLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalCustomers)
                    .addComponent(totalProducts))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalCustomersLabel)
                        .addComponent(totalCustomers))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalTransactionsLabel)
                        .addComponent(totalTransactions)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalProductsLabel)
                        .addComponent(totalProducts))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalIncomeLabel)
                        .addComponent(totalIncome)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardTitle;
    private javax.swing.JLabel totalCustomers;
    private javax.swing.JLabel totalCustomersLabel;
    private javax.swing.JLabel totalIncome;
    private javax.swing.JLabel totalIncomeLabel;
    private javax.swing.JLabel totalProducts;
    private javax.swing.JLabel totalProductsLabel;
    private javax.swing.JLabel totalTransactions;
    private javax.swing.JLabel totalTransactionsLabel;
    // End of variables declaration//GEN-END:variables
}
