/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author atha3
 */
public class TransactionHistory extends javax.swing.JPanel {

    /**
     * Creates new form TransactionHistory
     */
    public TransactionHistory() {
        initComponents();
        loadTransactionHistory();
    }
    
    private void loadTransactionHistory() {
        DefaultTableModel model = (DefaultTableModel) transactionHistoryTable.getModel();
        model.addRow(new Object[]{ 1, "INV-2342342", 100000, "Cash", "24-06-2025" });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTransactionDetails = new javax.swing.JDialog();
        transactionDetailsPanel = new javax.swing.JPanel();
        transactionDetailsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionDetailsTable = new javax.swing.JTable();
        labelDate = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        labelInvoiceNo = new javax.swing.JLabel();
        invoiceNo = new javax.swing.JTextField();
        labelCustomer = new javax.swing.JLabel();
        customer = new javax.swing.JTextField();
        labelTotal = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        payment = new javax.swing.JTextField();
        labelPayment = new javax.swing.JLabel();
        labelCashier = new javax.swing.JLabel();
        cashier = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        labelNote = new javax.swing.JLabel();
        transactionHistoryTitle = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        transactionHistoryTable = new javax.swing.JTable();
        btnShowDetails = new javax.swing.JButton();

        dialogTransactionDetails.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogTransactionDetails.setTitle("Transaction Details");
        dialogTransactionDetails.setModal(true);

        transactionDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        transactionDetailsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionDetailsTitle.setText("Transaction Details");

        transactionDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Product Name", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionDetailsTable);
        if (transactionDetailsTable.getColumnModel().getColumnCount() > 0) {
            transactionDetailsTable.getColumnModel().getColumn(0).setMinWidth(49);
            transactionDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            transactionDetailsTable.getColumnModel().getColumn(0).setMaxWidth(49);
        }

        labelDate.setText("Date");

        labelInvoiceNo.setText("Invoice No");

        labelCustomer.setText("Customer");

        labelTotal.setText("Total");

        labelPayment.setText("Payment");

        labelCashier.setText("Cashier");

        note.setColumns(18);
        note.setRows(4);
        note.setTabSize(7);
        jScrollPane2.setViewportView(note);

        labelNote.setText("Note");

        javax.swing.GroupLayout transactionDetailsPanelLayout = new javax.swing.GroupLayout(transactionDetailsPanel);
        transactionDetailsPanel.setLayout(transactionDetailsPanelLayout);
        transactionDetailsPanelLayout.setHorizontalGroup(
            transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(transactionDetailsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                        .addGap(78, 78, 78))
                    .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCustomer)
                            .addComponent(labelInvoiceNo)
                            .addComponent(labelDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(invoiceNo)
                            .addComponent(customer))
                        .addGap(18, 18, 18)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotal)
                            .addComponent(labelPayment)
                            .addComponent(labelCashier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total)
                            .addComponent(payment)
                            .addComponent(cashier, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        transactionDetailsPanelLayout.setVerticalGroup(
            transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                .addComponent(transactionDetailsTitle)
                .addGap(23, 23, 23)
                .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInvoiceNo)
                            .addComponent(invoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomer)))
                    .addComponent(labelNote)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCashier))))
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(transactionDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transactionDetailsPanelLayout.createSequentialGroup()
                    .addContainerGap(165, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout dialogTransactionDetailsLayout = new javax.swing.GroupLayout(dialogTransactionDetails.getContentPane());
        dialogTransactionDetails.getContentPane().setLayout(dialogTransactionDetailsLayout);
        dialogTransactionDetailsLayout.setHorizontalGroup(
            dialogTransactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransactionDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogTransactionDetailsLayout.setVerticalGroup(
            dialogTransactionDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransactionDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        transactionHistoryTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        transactionHistoryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionHistoryTitle.setText("Transaction History");

        transactionHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Invoice No", "Total", "Payment", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionHistoryTable.setMaximumSize(null);
        jScrollPane5.setViewportView(transactionHistoryTable);
        if (transactionHistoryTable.getColumnModel().getColumnCount() > 0) {
            transactionHistoryTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            transactionHistoryTable.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        btnShowDetails.setText("Show Details");
        btnShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnShowDetails)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(transactionHistoryTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionHistoryTitle)
                .addGap(27, 27, 27)
                .addComponent(btnShowDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailsActionPerformed
        int row = transactionHistoryTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No row is selected! Please select one row", "Select row",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String invoiceNo = transactionHistoryTable.getValueAt(row, 1).toString();
        
        dialogTransactionDetails.pack();
        dialogTransactionDetails.setLocationRelativeTo(this);
        dialogTransactionDetails.setVisible(true);
    }//GEN-LAST:event_btnShowDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowDetails;
    private javax.swing.JTextField cashier;
    private javax.swing.JTextField customer;
    private javax.swing.JTextField date;
    private javax.swing.JDialog dialogTransactionDetails;
    private javax.swing.JTextField invoiceNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelCashier;
    private javax.swing.JLabel labelCustomer;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelInvoiceNo;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelPayment;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTextArea note;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField total;
    private javax.swing.JPanel transactionDetailsPanel;
    private javax.swing.JTable transactionDetailsTable;
    private javax.swing.JLabel transactionDetailsTitle;
    private javax.swing.JTable transactionHistoryTable;
    private javax.swing.JLabel transactionHistoryTitle;
    // End of variables declaration//GEN-END:variables
}
